build:
  builder: "nixpacks"
  nixpacksPlan:
    providers:
      python: "poetry"

services:
  - name: compressor-bot
    build:
      dockerfile: Dockerfile
    deploy:
      startCommand: "python3 start.py"
      restartPolicyType: "ALWAYS"
    env:
      - key: APP_ID
        description: "Telegram API ID from my.telegram.org"
      - key: API_HASH
        description: "Telegram API Hash from my.telegram.org"
      - key: BOT_TOKEN
        description: "Telegram Bot Token from @BotFather"
      - key: LOG_CHANNEL
        description: "Telegram channel ID for logs"
      - key: OWNER_ID
        description: "Bot owner's Telegram ID"
    fs:
      size: "1GB"
    resources:
      cpu: 2
      memory: 1024
